# Use a base image with Java
FROM openjdk:21

# Set the working directory in the container
WORKDIR /app

# Copy the Spring Boot jar file to the container
COPY target/courses-api-backend-0.0.1-SNAPSHOT.jar app.jar

# Command to run the Spring Boot application
ENTRYPOINT ["java", "-jar", "app.jar"]